### PR TITLE
This fixes the script

### PR DESCRIPTION
**Pull request by spithash**
Coinmarketcap changed their website. This fixes it.

### CODE REVIEW

**Comment by skeith** [comment]
@flapjax how do you add PR to another PR ?

**Comment by flapjax** [comment]
@skeith I think you'd have to make a fork of spithash:master and PR to that. But, I'm merging this now, so you can just make a new PR on my repo if you want :)

**Comment by skeith** [comment]
I did, it was just aiohttp stuff, so I just rebase my PR and apply again? sorry, not git gud yet

**Comment by flapjax** [comment]
Yes I see your new PR now. I'm checking it out. I can probably merge that one with no problems.

**Pull request merged**
